language: node_js
node_js:
- 10
env:
  global:
    secure: nay7oDwWzGi1MwvAD0q3j8iwFvJj6foQZVzUN+nLeZE5+fvChJgriXpAg0B4E+s73GVc8lrYaiIK5tCftXK2Etvzsl+h9rlZgY2XMmDcJ3Ge8qqCzt+bkCUa9GMo0xhZ0mu9UbloP60g0JcUD4ned5Hvu9nVFpZLOZxGTKGPA/AtOT75+lFGbhvbQpWx2iWRpszJImz5Hg6ESUTaQBFkVcAxTB07wZBsfVJvSXd7/sAcOlOaKxUoim+UAEWGkFnd3HeH0jemql1BjlNL9e81f5Wqbqq1P63+oXuHzy7mwLo5I//m68Lt5Utrvr/pgki5H57e8vjKhBRQtyKBM3aca4CeHIkwpHaAu2Mo4RSWkpa9mCdf4Tt0qZqQBU8geIbALQz/JHW371k34Kng2+2zZDBZ/Sa2BzghPowKjY0FwpsA93NkdfOtcRwhZCYEio0NdfYWQZ6ooIvHiRoW6fIGtMNfnG7kheuuAHIRSaqVxzRIGAlKpZ9hL9y1bfJMdfWiSrgVXqiAbI7/Eguy/6Q5fvZgP9xeeyBa0g8mic/obNYBv4h/yMgIM74PT1VyaEd0fbtRph78IIDxVP7bWBBmdonSt00LKAFDqSMfnRRenF2rds5r24036l5degoSpRoofyCeUkFyT9KSYelgGE9uMFiaFrmV8l4Nugb5lNzdL28=
