export const Routes = {
  HOME: '/home',
  LOGIN: '/login',
  VIEW_DOCUMENTS: '/view-documents',
  ONBOARDING: '/get-started',
  PROFILE_HOME: '/profile-home',
  EDIT_QUESTIONNAIRE: '/edit-questionnaire',
  NEW_RESPONSE: '/edit-response',
  VIEW_RESPONSES: '/view-responses',
  CHANGE_PASSWORD: '/change-password',
  CHANGE_EMAIL: '/change-email',
  VIEW_RESPONSE: (id) => `/view-response/${id}`,
  USER_SETTINGS: '/user-settings',
  MANAGE_TEMPLATES: '/manage-templates',
  TEST_TEMPLATES: '/test-templates',
  TERMS_CONDITIONS: '/terms-and-conditions',
};
